[package]
name = "retrotools-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[[bin]]
name = "retrotools2026"
path = "src/main.rs"

[dependencies]
retrotools-common.workspace = true
retrotools-core.workspace = true
retrotools-plugin-api.workspace = true
retrotools-plugin-playlists.workspace = true
retrotools-plugin-bios.workspace = true
eframe = { version = "0.28", default-features = false, features = ["default_fonts", "glow", "persistence"] }
egui = "0.28"
egui_extras = { version = "0.28", features = ["all_loaders"] }
egui-notify = "0.15"
rfd = "0.14"
tracing.workspace = true
serde.workspace = true
