[package]
name = "retrotools-plugin-saves"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
retrotools-common.workspace = true
retrotools-core.workspace = true
retrotools-plugin-api.workspace = true
zip.workspace = true
chrono.workspace = true
