use retrotools_plugin_api::{Plugin, PluginContext, PluginOutcome, PluginResult};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// How sure the database is about a recommendation. Purely informational —
/// nothing in this crate changes behavior based on the value except how
/// it's surfaced to the user.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Confidence {
    High,
    Medium,
    Low,
}

impl std::fmt::Display for Confidence {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Confidence::High => write!(f, "high"),
            Confidence::Medium => write!(f, "medium"),
            Confidence::Low => write!(f, "low"),
        }
    }
}

/// One row of the local core-compatibility database: either a platform-wide
/// default (`game_name: None`) or an exception for one specific game.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CoreEntry {
    pub platform: String,
    pub game_name: Option<String>,
    pub core: String,
    pub confidence: Confidence,
    pub note: String,
    /// Set when this game is known to misbehave (crashes, wrong timing,
    /// missing audio, etc.) with the recommended core, independent of
    /// `confidence` — a low-confidence guess and a documented bug are two
    /// different things worth flagging differently.
    pub known_problematic: bool,
    /// libretro core option `key = "value"` pairs this game specifically
    /// needs, written as a per-game `.opt` override when non-empty.
    pub core_options: Vec<(String, String)>,
}

impl CoreEntry {
    pub fn validate(&self) -> Result<(), String> {
        if self.platform.trim().is_empty() {
            return Err("platform is required".into());
        }
        if self.core.trim().is_empty() {
            return Err("core is required".into());
        }
        Ok(())
    }
}

fn advisor_root() -> PathBuf {
    retrotools_common::config::plugin_data_dir_path("core-advisor")
        .unwrap_or_else(|_| PathBuf::from("core-advisor-data"))
}

fn database_path() -> PathBuf {
    advisor_root().join("database.json")
}

pub fn load_database() -> Result<Vec<CoreEntry>, String> {
    load_database_from(&database_path())
}

fn load_database_from(path: &Path) -> Result<Vec<CoreEntry>, String> {
    if !path.exists() {
        return Ok(Vec::new());
    }
    let raw = std::fs::read_to_string(path).map_err(|e| e.to_string())?;
    serde_json::from_str(&raw).map_err(|e| e.to_string())
}

pub fn save_database(entries: &[CoreEntry]) -> Result<(), String> {
    save_database_to(&database_path(), entries)
}

fn save_database_to(path: &Path, entries: &[CoreEntry]) -> Result<(), String> {
    for entry in entries {
        entry.validate()?;
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let json = serde_json::to_string_pretty(entries).map_err(|e| e.to_string())?;
    std::fs::write(path, json).map_err(|e| e.to_string())
}

/// Imports a user-supplied JSON file (same shape as [`save_database`]
/// writes) and replaces the stored database with it wholesale — this
/// project doesn't host or query any online service for this community
/// data, the user brings their own file.
pub fn import_database_file(path: &Path) -> Result<usize, String> {
    let raw = std::fs::read_to_string(path).map_err(|e| e.to_string())?;
    let entries: Vec<CoreEntry> = serde_json::from_str(&raw).map_err(|e| e.to_string())?;
    for entry in &entries {
        entry.validate()?;
    }
    save_database(&entries)?;
    Ok(entries.len())
}

/// Looks up the best recommendation for a game: an exact `platform` +
/// `game_name` entry wins over a platform-wide default (`game_name: None`).
pub fn find_recommendation<'a>(
    db: &'a [CoreEntry],
    platform: &str,
    game_name: &str,
) -> Option<&'a CoreEntry> {
    db.iter()
        .find(|e| e.platform == platform && e.game_name.as_deref() == Some(game_name))
        .or_else(|| {
            db.iter()
                .find(|e| e.platform == platform && e.game_name.is_none())
        })
}

/// The per-game core-options override path RetroArch expects:
/// `<core>/<game>.opt` directly under its config directory — unlike
/// overrides/remaps, per-game core options are not nested under a content
/// directory.
pub fn core_options_relative_path(core: &str, game_name: &str) -> PathBuf {
    PathBuf::from(core).join(format!("{game_name}.opt"))
}

fn core_options_content(options: &[(String, String)]) -> String {
    let mut out =
        String::from("# Generated by Retro Tools 2026 -- safe to delete, will be regenerated\n");
    for (key, value) in options {
        out.push_str(&format!("{key} = \"{value}\"\n"));
    }
    out
}

#[derive(Debug, Clone)]
pub struct AdvisorLine {
    pub game_name: String,
    pub core: String,
    pub confidence: Confidence,
    pub note: String,
    pub known_problematic: bool,
}

fn build_report(
    db: &[CoreEntry],
    platform: &str,
    matched_game_names: &[String],
) -> (Vec<AdvisorLine>, usize) {
    let mut lines = Vec::new();
    let mut without_recommendation = 0usize;
    for name in matched_game_names {
        match find_recommendation(db, platform, name) {
            Some(entry) => lines.push(AdvisorLine {
                game_name: name.clone(),
                core: entry.core.clone(),
                confidence: entry.confidence,
                note: entry.note.clone(),
                known_problematic: entry.known_problematic,
            }),
            None => without_recommendation += 1,
        }
    }
    (lines, without_recommendation)
}

fn report_text(lines: &[AdvisorLine]) -> String {
    let mut out = String::new();
    for line in lines {
        out.push_str(&format!(
            "{}\tcore={}\tconfidence={}\tproblematic={}\tnote={}\n",
            line.game_name, line.core, line.confidence, line.known_problematic, line.note
        ));
    }
    out
}

/// Cross-references the games actually matched by the most recent scan
/// (`ctx.match_report`, reused rather than re-scanned) against the local
/// core-compatibility database, and writes a plain-text report plus a
/// per-game `.opt` core-options override for every entry that has one.
pub struct CoreAdvisorPlugin;

impl Plugin for CoreAdvisorPlugin {
    fn id(&self) -> &'static str {
        "core-advisor-report"
    }

    fn name(&self) -> &'static str {
        "Core Compatibility Advisor"
    }

    fn description(&self) -> &'static str {
        "Recommend a libretro core per game and flag known-problematic combinations, using the local core database and the last scan's results."
    }

    fn run(&self, ctx: &PluginContext) -> PluginResult<PluginOutcome> {
        let report = ctx.match_report.ok_or("no scan result available — run a scan first (this plugin reuses it, it never re-scans)")?;
        let db = load_database()?;
        if db.is_empty() {
            return Err(
                "no core database imported yet — import one from Settings/Core Advisor first"
                    .into(),
            );
        }

        let matched_names: Vec<String> = report
            .matched
            .iter()
            .filter_map(|m| m.matched_game.clone())
            .collect();
        if matched_names.is_empty() {
            return Err("the last scan has no matched games to report on".into());
        }

        let (lines, without_recommendation) =
            build_report(&db, &ctx.gameset.platform, &matched_names);
        let problematic_count = lines.iter().filter(|l| l.known_problematic).count();
        let with_options: Vec<&AdvisorLine> = lines
            .iter()
            .filter(|l| {
                find_recommendation(&db, &ctx.gameset.platform, &l.game_name)
                    .map(|e| !e.core_options.is_empty())
                    .unwrap_or(false)
            })
            .collect();

        if ctx.dry_run {
            let summary = format!(
                "[dry run] would report on {} game(s): {} with a recommendation ({} flagged problematic, {} with per-game core options), {without_recommendation} with none",
                matched_names.len(),
                lines.len(),
                problematic_count,
                with_options.len()
            );
            return Ok(PluginOutcome {
                summary,
                files_written: Vec::new(),
            });
        }

        std::fs::create_dir_all(ctx.output_dir).map_err(|e| e.to_string())?;
        let report_path = ctx.output_dir.join("core-recommendations.txt");
        std::fs::write(&report_path, report_text(&lines)).map_err(|e| e.to_string())?;

        let mut files_written = vec![report_path];
        for line in &lines {
            if let Some(entry) = find_recommendation(&db, &ctx.gameset.platform, &line.game_name) {
                if !entry.core_options.is_empty() {
                    let rel = core_options_relative_path(&entry.core, &line.game_name);
                    let path = ctx.output_dir.join(&rel);
                    if let Some(parent) = path.parent() {
                        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
                    }
                    std::fs::write(&path, core_options_content(&entry.core_options))
                        .map_err(|e| e.to_string())?;
                    files_written.push(path);
                }
            }
        }

        let summary = format!(
            "reported on {} game(s): {} with a recommendation ({} flagged problematic, {} per-game core-options file(s) written), {without_recommendation} with no database entry",
            matched_names.len(),
            lines.len(),
            problematic_count,
            with_options.len()
        );
        Ok(PluginOutcome {
            summary,
            files_written,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use retrotools_core::hash::FileHashes;
    use retrotools_core::header::RomHeaderKind;
    use retrotools_core::{
        DatHeader, DatType, GameSet, MatchReport, RomMatch, RomStatus, ScannedRom,
    };

    fn temp_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "rt26-plugin-core-advisor-test-{name}-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    /// Several tests below read/write the real per-user database file
    /// (there's no test-only override for `advisor_root()`, same tradeoff
    /// as the shader plugin's associations store). Cargo runs tests in this
    /// crate on multiple threads by default, so without serializing access
    /// two tests racing on that one file produce flaky, order-dependent
    /// failures — this mutex makes them run one at a time instead.
    static DB_FILE_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn empty_gameset(platform: &str) -> GameSet {
        GameSet {
            platform: platform.into(),
            dat_name: "Test".into(),
            dat_version: "1".into(),
            dat_type: DatType::Custom,
            header: DatHeader::default(),
            games: Vec::new(),
        }
    }

    fn matched(game_name: &str) -> RomMatch {
        let file_name = format!("{game_name}.sfc");
        RomMatch {
            scanned: ScannedRom {
                platform_hint: "Test Platform".into(),
                source_path: PathBuf::from(&file_name),
                archive_entry: None,
                file_name: file_name.clone(),
                hashes: FileHashes {
                    size: 0,
                    crc32: "00000000".into(),
                    md5: String::new(),
                    sha1: String::new(),
                    sha256: String::new(),
                },
                headerless_hashes: None,
                header_kind: RomHeaderKind::None,
            },
            status: RomStatus::Matched,
            matched_game: Some(game_name.to_string()),
            matched_rom: Some(file_name),
        }
    }

    fn platform_default() -> CoreEntry {
        CoreEntry {
            platform: "Test Platform".into(),
            game_name: None,
            core: "generic_core".into(),
            confidence: Confidence::Medium,
            note: "default core for this platform".into(),
            known_problematic: false,
            core_options: Vec::new(),
        }
    }

    fn game_exception() -> CoreEntry {
        CoreEntry {
            platform: "Test Platform".into(),
            game_name: Some("Super Metroid".into()),
            core: "special_core".into(),
            confidence: Confidence::High,
            note: "needs a specific core for correct timing".into(),
            known_problematic: true,
            core_options: vec![("special_core_hack".into(), "enabled".into())],
        }
    }

    #[test]
    fn game_specific_entry_wins_over_platform_default() {
        let db = vec![platform_default(), game_exception()];
        let rec = find_recommendation(&db, "Test Platform", "Super Metroid").unwrap();
        assert_eq!(rec.core, "special_core");

        let default_rec = find_recommendation(&db, "Test Platform", "Some Other Game").unwrap();
        assert_eq!(default_rec.core, "generic_core");

        assert!(find_recommendation(&db, "Other Platform", "Anything").is_none());
    }

    #[test]
    fn database_round_trips_through_json() {
        let dir = temp_dir("db-roundtrip");
        let path = dir.join("database.json");
        let db = vec![platform_default(), game_exception()];
        save_database_to(&path, &db).unwrap();
        let loaded = load_database_from(&path).unwrap();
        assert_eq!(loaded, db);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn saving_an_entry_without_platform_or_core_is_rejected() {
        let dir = temp_dir("db-invalid");
        let path = dir.join("database.json");
        let mut bad = platform_default();
        bad.platform.clear();
        assert!(save_database_to(&path, &[bad]).is_err());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn import_replaces_the_stored_database() {
        let _guard = DB_FILE_LOCK.lock().unwrap();
        let source_dir = temp_dir("import-source");
        let source_file = source_dir.join("import.json");
        let db = vec![platform_default()];
        let json = serde_json::to_string_pretty(&db).unwrap();
        std::fs::write(&source_file, json).unwrap();

        let backup = load_database().unwrap();
        let count = import_database_file(&source_file).unwrap();
        assert_eq!(count, 1);
        let loaded = load_database().unwrap();
        assert_eq!(loaded, db);

        if backup.is_empty() {
            std::fs::remove_file(database_path()).ok();
        } else {
            save_database(&backup).unwrap();
        }
        std::fs::remove_dir_all(&source_dir).ok();
    }

    #[test]
    fn build_report_flags_problematic_games_and_counts_missing_entries() {
        let db = vec![platform_default(), game_exception()];
        let names = vec![
            "Super Metroid".to_string(),
            "Chrono Trigger".to_string(),
            "Unlisted Game".to_string(),
        ];
        // "Unlisted Game" only resolves via the platform default here since
        // the platform matches; simulate a genuinely unmapped platform game
        // by using a name that still hits the default entry, then check the
        // "no entry at all" branch with a platform that has no rows.
        let (lines, without) = build_report(&db, "Test Platform", &names);
        assert_eq!(lines.len(), 3);
        assert_eq!(without, 0);
        let metroid = lines
            .iter()
            .find(|l| l.game_name == "Super Metroid")
            .unwrap();
        assert!(metroid.known_problematic);
        assert_eq!(metroid.core, "special_core");

        let (lines2, without2) = build_report(&db, "No Rows Platform", &names);
        assert!(lines2.is_empty());
        assert_eq!(without2, 3);
    }

    #[test]
    fn plugin_errors_clearly_without_a_match_report() {
        let gs = empty_gameset("Test Platform");
        let output = temp_dir("no-report-output");
        let ctx = PluginContext {
            gameset: &gs,
            kept_game_names: &[],
            source_dir: None,
            output_dir: &output,
            match_report: None,
            dry_run: false,
        };
        let err = CoreAdvisorPlugin.run(&ctx).unwrap_err();
        assert!(err.contains("run a scan first"));
        std::fs::remove_dir_all(&output).ok();
    }

    #[test]
    fn plugin_run_writes_report_and_core_options_end_to_end() {
        let _guard = DB_FILE_LOCK.lock().unwrap();
        let backup = load_database().unwrap();
        let db = vec![platform_default(), game_exception()];
        save_database(&db).unwrap();

        let gs = empty_gameset("Test Platform");
        let output = temp_dir("run-output");
        let report = MatchReport {
            platform: "Test Platform".into(),
            matched: vec![matched("Super Metroid"), matched("Chrono Trigger")],
            corrupt: Vec::new(),
            unknown: Vec::new(),
            missing: Vec::new(),
        };
        let ctx = PluginContext {
            gameset: &gs,
            kept_game_names: &[],
            source_dir: None,
            output_dir: &output,
            match_report: Some(&report),
            dry_run: false,
        };
        let outcome = CoreAdvisorPlugin.run(&ctx).unwrap();
        assert!(outcome.summary.contains("1 flagged problematic"));
        assert!(outcome.summary.contains("1 per-game core-options"));

        let report_text = std::fs::read_to_string(output.join("core-recommendations.txt")).unwrap();
        assert!(report_text.contains("Super Metroid"));
        assert!(report_text.contains("special_core"));
        assert!(report_text.contains("problematic=true"));

        let opt_path = output.join("special_core").join("Super Metroid.opt");
        assert!(opt_path.is_file());
        let opt_content = std::fs::read_to_string(&opt_path).unwrap();
        assert!(opt_content.contains("special_core_hack = \"enabled\""));

        assert!(!output
            .join("generic_core")
            .join("Chrono Trigger.opt")
            .exists());

        if backup.is_empty() {
            std::fs::remove_file(database_path()).ok();
        } else {
            save_database(&backup).unwrap();
        }
        std::fs::remove_dir_all(&output).ok();
    }

    #[test]
    fn dry_run_reports_the_plan_without_writing_anything() {
        let _guard = DB_FILE_LOCK.lock().unwrap();
        let backup = load_database().unwrap();
        let db = vec![platform_default(), game_exception()];
        save_database(&db).unwrap();

        let gs = empty_gameset("Test Platform");
        let output = temp_dir("dry-run-output");
        let report = MatchReport {
            platform: "Test Platform".into(),
            matched: vec![matched("Super Metroid")],
            corrupt: Vec::new(),
            unknown: Vec::new(),
            missing: Vec::new(),
        };
        let ctx = PluginContext {
            gameset: &gs,
            kept_game_names: &[],
            source_dir: None,
            output_dir: &output,
            match_report: Some(&report),
            dry_run: true,
        };
        let outcome = CoreAdvisorPlugin.run(&ctx).unwrap();
        assert!(outcome.summary.starts_with("[dry run]"));
        assert!(!output.join("core-recommendations.txt").exists());

        if backup.is_empty() {
            std::fs::remove_file(database_path()).ok();
        } else {
            save_database(&backup).unwrap();
        }
        std::fs::remove_dir_all(&output).ok();
    }
}
