[package]
name = "retrotools-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
retrotools-common.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
quick-xml.workspace = true
zip.workspace = true
rusqlite.workspace = true
rayon.workspace = true
walkdir.workspace = true
crc32fast.workspace = true
md-5.workspace = true
sha1.workspace = true
sha2.workspace = true
tar.workspace = true
sevenz-rust.workspace = true
chrono.workspace = true
notify.workspace = true
ureq.workspace = true
printpdf.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "hashing"
harness = false

[[bench]]
name = "dat_parsing"
harness = false
